# Generated by Django 5.2.7 on 2025-10-14 17:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='شماره تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درخواست شماره تلفن',
                'verbose_name_plural': 'درخواست\u200cهای شماره تلفن',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='نام کاربری')),
                ('telegram_Id', models.TextField(verbose_name='ایدی تلگرام')),
                ('image_link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'داده کاربر',
                'verbose_name_plural': 'داده\u200cهای کاربران',
                'ordering': ['-created_at'],
            },
        ),
    ]
