# Generated by Django 5.2.7 on 2025-11-08 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sherlockresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SherlockSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ جستجو')),
                ('status', models.CharField(choices=[('pending', 'در حال جستجو'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='نتایج')),
                ('total_found', models.IntegerField(default=0, verbose_name='تعداد یافت شده')),
            ],
            options={
                'verbose_name': 'جستجوی شرلوک',
                'verbose_name_plural': 'جستجوهای شرلوک',
                'ordering': ['-search_date'],
            },
        ),
        migrations.DeleteModel(
            name='SherlockResult',
        ),
    ]
